### ISSUE TITLE
"update" description might be confusing for users 

### ISSUE THREAD

**Issue by thedirk** [OpenPoti/openpoti-toolkit#12]
it reads: "Command to update the annotations, must be run making edits to base text." 

when run, it reads: "Updating annotations to [Work ID]". 

from a user perspective, i think this might be confusing. the user is making changes to the base text. and updating the base text. right? if i'm not mistaken, it is then the software that—based on changes to the base text—makes updates to the _index_ in the annotation layers. 

if i am a normal user, i think i don't actually care about this. i wouldn't know how it works. in my mind, i am updating the base layer (not the annotations). so an improvement could be: 

"Command to update the base text with your edits." 
"Updating [Work ID] base text".

**Comment by 10zinten** [comment]
Yeah that sound much better and less confusing. 

Thanks !

**Comment by 10zinten** [comment]
Its fixed !
