### ISSUE TITLE
What would be the output for dmp_find()

### ISSUE THREAD

**Issue by 10zinten** [OpenPoti/openpoti-toolkit#2]
https://github.com/OpenPoti/openpoti-toolkit/blob/edcfdf76c738a701962e8fd0a4b21118909be1ca/openpoti/blupdate.py#L134

What would be the output for `context = (ghi, jkl)` and `dstcoordestimate = 8`, computed with `srcblcoord = 7` based on the same example in the [code](https://github.com/OpenPoti/openpoti-toolkit/blob/ade0dbcf3a40c7ef8a1a3caab563b6885dbc23f0/openpoti/blupdate.py#L34)

**Comment by eroux** [comment]
well, in that case I don't know if dmp is going to be able to find a match, but if it does I guess it should be 6... but don't write that kind of code yourself! It should really be using dmp's algorihms, they're pretty advanced

**Comment by eroux** [comment]
sorry, 7, not 6... but in any case, if dmp doesn't find a match, the function should return `-1` as a result. In some cases there's just no possible match, that's ok

**Comment by 10zinten** [comment]
Okay got it, thanks !
